
# Future Work {#future}

## NSFG / High-risk population
See Issue [#94](https://github.com/statnet/SHAMP/issues/94). Martina noted that data cannot be combined in ergm.ego until the formats are similar for the stats for ERGM.

## Modelling immigrant spouses who live in home country
See Issue [#151](https://github.com/statnet/SHAMP/issues/151).

## Life expectancy for HIV + 
Issue [#60](https://github.com/statnet/SHAMP/issues/60) links to a paper on "Population-Based Estimates of Life Expectancy After HIV Diagnosis: United States 2008-2011".

## Nodematched Cohabs too low for B/BI/H/HI

See Issues [#149](https://github.com/statnet/SHAMP/issues/149) and the comment Martina made in the Diagnostics Sept 2018 model run in Issue [#146](https://github.com/statnet/SHAMP/issues/146#issuecomment-424153331). See the [Model Cohab section](#cohaberg) to see how the terms plateau low - they also were low in the Spring 2019 models.


## Age related within and cross-net concurrency

Focusing on an agecat3 x deg.pers interaction would be worth exploring in the future  (Issue [#102](https://github.com/statnet/SHAMP/issues/102)).

## Removing alters with missing data

Currently - 5% of nodes are missing information on age (See Issue [#120](https://github.com/statnet/SHAMP/issues/120)). 

This raised an issue of deleting alters to get the ergms to run. Jeanette wants to explore if there are problems with missing data and dropping alters on the initial network. Full discussion of this, and consequences for WHAMP are explored in Issue [#62](https://github.com/statnet/SHAMP/issues/62).


## Add 10 year death rate data

See [Issue #61](https://github.com/statnet/SHAMP/issues/61).
