--- 
title: "SHAMP: Seattle HIV/AIDS Modeling Project"
author: "Jeanette Birnbaum"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output:
    bookdown::gitbook: 
        config:
            toc:
                collapse: section
bibliography: [references.bib, reference-packages.bib]
biblio-style: apalike
link-citations: yes
description: "Egocentric data analysis and network model estimation and diagnostics for the Seattle HIV/AIDS Modeling Project (SHAMP)."
---

# Overview
Note that the sections below are denoted with bold, not section headings, because collapse: section in the yaml will work for regular chapters but not the index.Rmd chapter.

To add custom chapters, simply create new .Rmd files in this folder and add their names in the desired point in the list of .Rmd files in _bookdown.yml.

The chapters included are:


Chapter | Content
-------------- | ------------------------------------------
Setup | Reads in the "Parameters.R" file that establishes the baseline variables by which the descriptive statistics will be stratified. Load packages and shows sessionInfo.
Introduction | Information on the project purpose, background information on datasets that were used, and other datasets that were considered.
Data | Notes on (and/or links to other documents containing notes on) how the raw data were prepared for this analysis. 
Ego Characteristics | Demographic and other characteristics of the egos.
Degree | Momentary degree (e.g., extant/active ties only) and concurrency of egos.
Mixing | Mixing matrices of egos and alters on nodal attributes
One-Times | Rates of one-time relationships
Edge Age | Age of active/extant ties
Decisions | Analytical decisions made after considering the descriptives, including model specification choices.
ERGMs | ERGM fits and diagnostics
Parameters | List of parameter values for modeling. See https://norcalbiostat.netlify.com/post/fancifying-excel-tables-in-r-markdown-with-kable-extra/ for importing from an Excel sheet and maintaining hyperlinks.
Appendix | Any appendices
Tables & Figures | Hyperlinked index of tables and figures, by caption
References | Reference list


